// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Base.proto

#include "Base.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Base {
class msgNullDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<msgNull>
      _instance;
} _msgNull_default_instance_;
class msgHeartbeartServerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<msgHeartbeartServer>
      _instance;
} _msgHeartbeartServer_default_instance_;
class msgHeartbeartClientDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<msgHeartbeartClient>
      _instance;
} _msgHeartbeartClient_default_instance_;
}  // namespace Base
namespace protobuf_Base_2eproto {
static void InitDefaultsmsgNull() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Base::_msgNull_default_instance_;
    new (ptr) ::Base::msgNull();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Base::msgNull::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_msgNull =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmsgNull}, {}};

static void InitDefaultsmsgHeartbeartServer() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Base::_msgHeartbeartServer_default_instance_;
    new (ptr) ::Base::msgHeartbeartServer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Base::msgHeartbeartServer::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_msgHeartbeartServer =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmsgHeartbeartServer}, {}};

static void InitDefaultsmsgHeartbeartClient() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Base::_msgHeartbeartClient_default_instance_;
    new (ptr) ::Base::msgHeartbeartClient();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Base::msgHeartbeartClient::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_msgHeartbeartClient =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmsgHeartbeartClient}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_msgNull.base);
  ::google::protobuf::internal::InitSCC(&scc_info_msgHeartbeartServer.base);
  ::google::protobuf::internal::InitSCC(&scc_info_msgHeartbeartClient.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgNull, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgNull, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgHeartbeartServer, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgHeartbeartServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgHeartbeartServer, dwtimestamp_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgHeartbeartClient, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgHeartbeartClient, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Base::msgHeartbeartClient, dwtimestamp_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::Base::msgNull)},
  { 5, 11, sizeof(::Base::msgHeartbeartServer)},
  { 12, 18, sizeof(::Base::msgHeartbeartClient)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Base::_msgNull_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Base::_msgHeartbeartServer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Base::_msgHeartbeartClient_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Base.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\nBase.proto\022\004Base\"\t\n\007msgNull\"*\n\023msgHear"
      "tbeartServer\022\023\n\013dwTimestamp\030\001 \001(\004\"*\n\023msg"
      "HeartbeartClient\022\023\n\013dwTimestamp\030\001 \001(\004"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 117);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Base.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Base_2eproto
namespace Base {

// ===================================================================

void msgNull::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

msgNull::msgNull()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Base_2eproto::scc_info_msgNull.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Base.msgNull)
}
msgNull::msgNull(const msgNull& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Base.msgNull)
}

void msgNull::SharedCtor() {
}

msgNull::~msgNull() {
  // @@protoc_insertion_point(destructor:Base.msgNull)
  SharedDtor();
}

void msgNull::SharedDtor() {
}

void msgNull::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* msgNull::descriptor() {
  ::protobuf_Base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Base_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const msgNull& msgNull::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Base_2eproto::scc_info_msgNull.base);
  return *internal_default_instance();
}


void msgNull::Clear() {
// @@protoc_insertion_point(message_clear_start:Base.msgNull)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool msgNull::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Base.msgNull)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:Base.msgNull)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Base.msgNull)
  return false;
#undef DO_
}

void msgNull::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Base.msgNull)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Base.msgNull)
}

::google::protobuf::uint8* msgNull::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Base.msgNull)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Base.msgNull)
  return target;
}

size_t msgNull::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Base.msgNull)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void msgNull::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Base.msgNull)
  GOOGLE_DCHECK_NE(&from, this);
  const msgNull* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const msgNull>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Base.msgNull)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Base.msgNull)
    MergeFrom(*source);
  }
}

void msgNull::MergeFrom(const msgNull& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Base.msgNull)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void msgNull::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Base.msgNull)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgNull::CopyFrom(const msgNull& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Base.msgNull)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgNull::IsInitialized() const {
  return true;
}

void msgNull::Swap(msgNull* other) {
  if (other == this) return;
  InternalSwap(other);
}
void msgNull::InternalSwap(msgNull* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata msgNull::GetMetadata() const {
  protobuf_Base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Base_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void msgHeartbeartServer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int msgHeartbeartServer::kDwTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

msgHeartbeartServer::msgHeartbeartServer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Base_2eproto::scc_info_msgHeartbeartServer.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Base.msgHeartbeartServer)
}
msgHeartbeartServer::msgHeartbeartServer(const msgHeartbeartServer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  dwtimestamp_ = from.dwtimestamp_;
  // @@protoc_insertion_point(copy_constructor:Base.msgHeartbeartServer)
}

void msgHeartbeartServer::SharedCtor() {
  dwtimestamp_ = GOOGLE_ULONGLONG(0);
}

msgHeartbeartServer::~msgHeartbeartServer() {
  // @@protoc_insertion_point(destructor:Base.msgHeartbeartServer)
  SharedDtor();
}

void msgHeartbeartServer::SharedDtor() {
}

void msgHeartbeartServer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* msgHeartbeartServer::descriptor() {
  ::protobuf_Base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Base_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const msgHeartbeartServer& msgHeartbeartServer::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Base_2eproto::scc_info_msgHeartbeartServer.base);
  return *internal_default_instance();
}


void msgHeartbeartServer::Clear() {
// @@protoc_insertion_point(message_clear_start:Base.msgHeartbeartServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dwtimestamp_ = GOOGLE_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool msgHeartbeartServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Base.msgHeartbeartServer)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 dwTimestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_dwtimestamp();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &dwtimestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Base.msgHeartbeartServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Base.msgHeartbeartServer)
  return false;
#undef DO_
}

void msgHeartbeartServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Base.msgHeartbeartServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 dwTimestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->dwtimestamp(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Base.msgHeartbeartServer)
}

::google::protobuf::uint8* msgHeartbeartServer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Base.msgHeartbeartServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 dwTimestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->dwtimestamp(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Base.msgHeartbeartServer)
  return target;
}

size_t msgHeartbeartServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Base.msgHeartbeartServer)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional uint64 dwTimestamp = 1;
  if (has_dwtimestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->dwtimestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void msgHeartbeartServer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Base.msgHeartbeartServer)
  GOOGLE_DCHECK_NE(&from, this);
  const msgHeartbeartServer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const msgHeartbeartServer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Base.msgHeartbeartServer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Base.msgHeartbeartServer)
    MergeFrom(*source);
  }
}

void msgHeartbeartServer::MergeFrom(const msgHeartbeartServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Base.msgHeartbeartServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_dwtimestamp()) {
    set_dwtimestamp(from.dwtimestamp());
  }
}

void msgHeartbeartServer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Base.msgHeartbeartServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgHeartbeartServer::CopyFrom(const msgHeartbeartServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Base.msgHeartbeartServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgHeartbeartServer::IsInitialized() const {
  return true;
}

void msgHeartbeartServer::Swap(msgHeartbeartServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void msgHeartbeartServer::InternalSwap(msgHeartbeartServer* other) {
  using std::swap;
  swap(dwtimestamp_, other->dwtimestamp_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata msgHeartbeartServer::GetMetadata() const {
  protobuf_Base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Base_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void msgHeartbeartClient::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int msgHeartbeartClient::kDwTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

msgHeartbeartClient::msgHeartbeartClient()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Base_2eproto::scc_info_msgHeartbeartClient.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Base.msgHeartbeartClient)
}
msgHeartbeartClient::msgHeartbeartClient(const msgHeartbeartClient& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  dwtimestamp_ = from.dwtimestamp_;
  // @@protoc_insertion_point(copy_constructor:Base.msgHeartbeartClient)
}

void msgHeartbeartClient::SharedCtor() {
  dwtimestamp_ = GOOGLE_ULONGLONG(0);
}

msgHeartbeartClient::~msgHeartbeartClient() {
  // @@protoc_insertion_point(destructor:Base.msgHeartbeartClient)
  SharedDtor();
}

void msgHeartbeartClient::SharedDtor() {
}

void msgHeartbeartClient::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* msgHeartbeartClient::descriptor() {
  ::protobuf_Base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Base_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const msgHeartbeartClient& msgHeartbeartClient::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Base_2eproto::scc_info_msgHeartbeartClient.base);
  return *internal_default_instance();
}


void msgHeartbeartClient::Clear() {
// @@protoc_insertion_point(message_clear_start:Base.msgHeartbeartClient)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dwtimestamp_ = GOOGLE_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool msgHeartbeartClient::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Base.msgHeartbeartClient)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 dwTimestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_dwtimestamp();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &dwtimestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Base.msgHeartbeartClient)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Base.msgHeartbeartClient)
  return false;
#undef DO_
}

void msgHeartbeartClient::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Base.msgHeartbeartClient)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 dwTimestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->dwtimestamp(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Base.msgHeartbeartClient)
}

::google::protobuf::uint8* msgHeartbeartClient::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Base.msgHeartbeartClient)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 dwTimestamp = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->dwtimestamp(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Base.msgHeartbeartClient)
  return target;
}

size_t msgHeartbeartClient::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Base.msgHeartbeartClient)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional uint64 dwTimestamp = 1;
  if (has_dwtimestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->dwtimestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void msgHeartbeartClient::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Base.msgHeartbeartClient)
  GOOGLE_DCHECK_NE(&from, this);
  const msgHeartbeartClient* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const msgHeartbeartClient>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Base.msgHeartbeartClient)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Base.msgHeartbeartClient)
    MergeFrom(*source);
  }
}

void msgHeartbeartClient::MergeFrom(const msgHeartbeartClient& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Base.msgHeartbeartClient)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_dwtimestamp()) {
    set_dwtimestamp(from.dwtimestamp());
  }
}

void msgHeartbeartClient::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Base.msgHeartbeartClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgHeartbeartClient::CopyFrom(const msgHeartbeartClient& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Base.msgHeartbeartClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgHeartbeartClient::IsInitialized() const {
  return true;
}

void msgHeartbeartClient::Swap(msgHeartbeartClient* other) {
  if (other == this) return;
  InternalSwap(other);
}
void msgHeartbeartClient::InternalSwap(msgHeartbeartClient* other) {
  using std::swap;
  swap(dwtimestamp_, other->dwtimestamp_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata msgHeartbeartClient::GetMetadata() const {
  protobuf_Base_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Base_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Base
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Base::msgNull* Arena::CreateMaybeMessage< ::Base::msgNull >(Arena* arena) {
  return Arena::CreateInternal< ::Base::msgNull >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Base::msgHeartbeartServer* Arena::CreateMaybeMessage< ::Base::msgHeartbeartServer >(Arena* arena) {
  return Arena::CreateInternal< ::Base::msgHeartbeartServer >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Base::msgHeartbeartClient* Arena::CreateMaybeMessage< ::Base::msgHeartbeartClient >(Arena* arena) {
  return Arena::CreateInternal< ::Base::msgHeartbeartClient >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
