// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoServer.proto

#include "DemoServer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace Demo {
class msgUserLoginReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<msgUserLoginReq>
      _instance;
} _msgUserLoginReq_default_instance_;
class msgUserLoginRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<msgUserLoginRsp>
      _instance;
} _msgUserLoginRsp_default_instance_;
class msgRetcodeRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<msgRetcodeRsp>
      _instance;
} _msgRetcodeRsp_default_instance_;
}  // namespace Demo
namespace protobuf_DemoServer_2eproto {
static void InitDefaultsmsgUserLoginReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Demo::_msgUserLoginReq_default_instance_;
    new (ptr) ::Demo::msgUserLoginReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Demo::msgUserLoginReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_msgUserLoginReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmsgUserLoginReq}, {}};

static void InitDefaultsmsgUserLoginRsp() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Demo::_msgUserLoginRsp_default_instance_;
    new (ptr) ::Demo::msgUserLoginRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Demo::msgUserLoginRsp::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_msgUserLoginRsp =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmsgUserLoginRsp}, {}};

static void InitDefaultsmsgRetcodeRsp() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Demo::_msgRetcodeRsp_default_instance_;
    new (ptr) ::Demo::msgRetcodeRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Demo::msgRetcodeRsp::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_msgRetcodeRsp =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmsgRetcodeRsp}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_msgUserLoginReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_msgUserLoginRsp.base);
  ::google::protobuf::internal::InitSCC(&scc_info_msgRetcodeRsp.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgUserLoginReq, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgUserLoginReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgUserLoginRsp, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgUserLoginRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgRetcodeRsp, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgRetcodeRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Demo::msgRetcodeRsp, dwret_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 5, sizeof(::Demo::msgUserLoginReq)},
  { 5, 10, sizeof(::Demo::msgUserLoginRsp)},
  { 10, 16, sizeof(::Demo::msgRetcodeRsp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Demo::_msgUserLoginReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Demo::_msgUserLoginRsp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Demo::_msgRetcodeRsp_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "DemoServer.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020DemoServer.proto\022\004Demo\"\021\n\017msgUserLogin"
      "Req\"\021\n\017msgUserLoginRsp\"\036\n\rmsgRetcodeRsp\022"
      "\r\n\005dwRet\030\001 \002(\r"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DemoServer.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_DemoServer_2eproto
namespace Demo {

// ===================================================================

void msgUserLoginReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

msgUserLoginReq::msgUserLoginReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DemoServer_2eproto::scc_info_msgUserLoginReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Demo.msgUserLoginReq)
}
msgUserLoginReq::msgUserLoginReq(const msgUserLoginReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Demo.msgUserLoginReq)
}

void msgUserLoginReq::SharedCtor() {
}

msgUserLoginReq::~msgUserLoginReq() {
  // @@protoc_insertion_point(destructor:Demo.msgUserLoginReq)
  SharedDtor();
}

void msgUserLoginReq::SharedDtor() {
}

void msgUserLoginReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* msgUserLoginReq::descriptor() {
  ::protobuf_DemoServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DemoServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const msgUserLoginReq& msgUserLoginReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DemoServer_2eproto::scc_info_msgUserLoginReq.base);
  return *internal_default_instance();
}


void msgUserLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:Demo.msgUserLoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool msgUserLoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Demo.msgUserLoginReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:Demo.msgUserLoginReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Demo.msgUserLoginReq)
  return false;
#undef DO_
}

void msgUserLoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Demo.msgUserLoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Demo.msgUserLoginReq)
}

::google::protobuf::uint8* msgUserLoginReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Demo.msgUserLoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Demo.msgUserLoginReq)
  return target;
}

size_t msgUserLoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Demo.msgUserLoginReq)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void msgUserLoginReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Demo.msgUserLoginReq)
  GOOGLE_DCHECK_NE(&from, this);
  const msgUserLoginReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const msgUserLoginReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Demo.msgUserLoginReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Demo.msgUserLoginReq)
    MergeFrom(*source);
  }
}

void msgUserLoginReq::MergeFrom(const msgUserLoginReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Demo.msgUserLoginReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void msgUserLoginReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Demo.msgUserLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgUserLoginReq::CopyFrom(const msgUserLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Demo.msgUserLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgUserLoginReq::IsInitialized() const {
  return true;
}

void msgUserLoginReq::Swap(msgUserLoginReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void msgUserLoginReq::InternalSwap(msgUserLoginReq* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata msgUserLoginReq::GetMetadata() const {
  protobuf_DemoServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DemoServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void msgUserLoginRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

msgUserLoginRsp::msgUserLoginRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DemoServer_2eproto::scc_info_msgUserLoginRsp.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Demo.msgUserLoginRsp)
}
msgUserLoginRsp::msgUserLoginRsp(const msgUserLoginRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Demo.msgUserLoginRsp)
}

void msgUserLoginRsp::SharedCtor() {
}

msgUserLoginRsp::~msgUserLoginRsp() {
  // @@protoc_insertion_point(destructor:Demo.msgUserLoginRsp)
  SharedDtor();
}

void msgUserLoginRsp::SharedDtor() {
}

void msgUserLoginRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* msgUserLoginRsp::descriptor() {
  ::protobuf_DemoServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DemoServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const msgUserLoginRsp& msgUserLoginRsp::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DemoServer_2eproto::scc_info_msgUserLoginRsp.base);
  return *internal_default_instance();
}


void msgUserLoginRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:Demo.msgUserLoginRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool msgUserLoginRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Demo.msgUserLoginRsp)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:Demo.msgUserLoginRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Demo.msgUserLoginRsp)
  return false;
#undef DO_
}

void msgUserLoginRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Demo.msgUserLoginRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Demo.msgUserLoginRsp)
}

::google::protobuf::uint8* msgUserLoginRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Demo.msgUserLoginRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Demo.msgUserLoginRsp)
  return target;
}

size_t msgUserLoginRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Demo.msgUserLoginRsp)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void msgUserLoginRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Demo.msgUserLoginRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const msgUserLoginRsp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const msgUserLoginRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Demo.msgUserLoginRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Demo.msgUserLoginRsp)
    MergeFrom(*source);
  }
}

void msgUserLoginRsp::MergeFrom(const msgUserLoginRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Demo.msgUserLoginRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void msgUserLoginRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Demo.msgUserLoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgUserLoginRsp::CopyFrom(const msgUserLoginRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Demo.msgUserLoginRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgUserLoginRsp::IsInitialized() const {
  return true;
}

void msgUserLoginRsp::Swap(msgUserLoginRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void msgUserLoginRsp::InternalSwap(msgUserLoginRsp* other) {
  using std::swap;
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata msgUserLoginRsp::GetMetadata() const {
  protobuf_DemoServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DemoServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void msgRetcodeRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int msgRetcodeRsp::kDwRetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

msgRetcodeRsp::msgRetcodeRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DemoServer_2eproto::scc_info_msgRetcodeRsp.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Demo.msgRetcodeRsp)
}
msgRetcodeRsp::msgRetcodeRsp(const msgRetcodeRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  dwret_ = from.dwret_;
  // @@protoc_insertion_point(copy_constructor:Demo.msgRetcodeRsp)
}

void msgRetcodeRsp::SharedCtor() {
  dwret_ = 0u;
}

msgRetcodeRsp::~msgRetcodeRsp() {
  // @@protoc_insertion_point(destructor:Demo.msgRetcodeRsp)
  SharedDtor();
}

void msgRetcodeRsp::SharedDtor() {
}

void msgRetcodeRsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* msgRetcodeRsp::descriptor() {
  ::protobuf_DemoServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DemoServer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const msgRetcodeRsp& msgRetcodeRsp::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DemoServer_2eproto::scc_info_msgRetcodeRsp.base);
  return *internal_default_instance();
}


void msgRetcodeRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:Demo.msgRetcodeRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dwret_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool msgRetcodeRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Demo.msgRetcodeRsp)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 dwRet = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_dwret();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dwret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Demo.msgRetcodeRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Demo.msgRetcodeRsp)
  return false;
#undef DO_
}

void msgRetcodeRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Demo.msgRetcodeRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 dwRet = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->dwret(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Demo.msgRetcodeRsp)
}

::google::protobuf::uint8* msgRetcodeRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Demo.msgRetcodeRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 dwRet = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->dwret(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Demo.msgRetcodeRsp)
  return target;
}

size_t msgRetcodeRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Demo.msgRetcodeRsp)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required uint32 dwRet = 1;
  if (has_dwret()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dwret());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void msgRetcodeRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Demo.msgRetcodeRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const msgRetcodeRsp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const msgRetcodeRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Demo.msgRetcodeRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Demo.msgRetcodeRsp)
    MergeFrom(*source);
  }
}

void msgRetcodeRsp::MergeFrom(const msgRetcodeRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Demo.msgRetcodeRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_dwret()) {
    set_dwret(from.dwret());
  }
}

void msgRetcodeRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Demo.msgRetcodeRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgRetcodeRsp::CopyFrom(const msgRetcodeRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Demo.msgRetcodeRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgRetcodeRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void msgRetcodeRsp::Swap(msgRetcodeRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void msgRetcodeRsp::InternalSwap(msgRetcodeRsp* other) {
  using std::swap;
  swap(dwret_, other->dwret_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata msgRetcodeRsp::GetMetadata() const {
  protobuf_DemoServer_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DemoServer_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Demo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Demo::msgUserLoginReq* Arena::CreateMaybeMessage< ::Demo::msgUserLoginReq >(Arena* arena) {
  return Arena::CreateInternal< ::Demo::msgUserLoginReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Demo::msgUserLoginRsp* Arena::CreateMaybeMessage< ::Demo::msgUserLoginRsp >(Arena* arena) {
  return Arena::CreateInternal< ::Demo::msgUserLoginRsp >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Demo::msgRetcodeRsp* Arena::CreateMaybeMessage< ::Demo::msgRetcodeRsp >(Arena* arena) {
  return Arena::CreateInternal< ::Demo::msgRetcodeRsp >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
